[dependencies]
langs = "langs"
shells = "shells"
nvims = "nvims"
yazi = "yazi"


[links]
"navi" = "~/.local/share/navi/cheats"
"git" = "~/.config/git"
"gdb" = "~/.config/gdb"
"macchina" = "~/.config/macchina"
"gitui" = "~/.config/gitui"
"mise" = "~/.config/mise"
"kde"="~/.config/kde"
"wezterm"="~/.config/wezterm"
