# subs = [
#     # 
#     "cargo",
#     "go",
#     "yazi",
# ]


[links]
gdb = "~/.config/gdb"
navi = "~/.local/share/navi/cheats"
LazyVim = "~/.config/LazyVim"
git = "~/.config/git"
"starship.toml" = "~/.config/starship.toml"
