[dependencies]
go = "langs/go"
rust = "langs/rust"
zsh = "shells/zsh"

[links]
"navi" = "~/.local/share/navi/cheats"
"yazi" = "~/.config/yazi"
"git" = "~/.config/git"
"gdb" = "~/.config/gdb"
"LazyVim" = "~/.config/LazyVim"
