[dependencies]
langs = "langs"
shells = "shells"

[links]
"navi" = "~/.local/share/navi/cheats"
"yazi" = "~/.config/yazi"
"git" = "~/.config/git"
"gdb" = "~/.config/gdb"
"LazyVim" = "~/.config/LazyVim"
