#!/bin/zsh
source "$HOME/.config/shells/zsh/init.zsh"



# # >>> fishros initialize >>>
# source /opt/ros/humble/setup.zsh
# # <<< fishros initialize <<<

# 安全 source - 文件不存在时不报错
[[ -f "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"
