[tools]
go = "1.23.4"
node = "latest"
pnpm = "10.20.0"
zig = "latest"

[settings]
experimental = true

[settings.python]
uv_venv_auto = true

[env]
QODERCLI_TOKEN = "pt-AyycygyMblU5LzcIqlmffq9G_019c8148-91ce-73cb-87b5-7f4f0801218a"
