#!/usr/bin/env bash

set -euxo pipefail

LLVM_VERSION=$1
LLVM_PATH="/usr/lib/llvm-${LLVM_VERSION}"
sudo wget https://apt.llvm.org/llvm.sh | sudo sh -s -- "${LLVM_VERSION}"
sudo ln -sfn "${LLVM_PATH}" /usr/lib/llvm
sudo ln -sfn "${LLVM_PATH}/bin/clang" /usr/local/bin/clang
    