#!/usr/bin/env python

import os

def main():
    # list files in /usr/lib/
    files=os.listdir("/usr/lib")
    # filter files ,only retain file matching llvm-<number>
    files=filter(lambda x: x.startswith("llvm-"),files)
    # map files to version number
    versions=list(map(lambda x: x[5:],files))
    # check if exists /usr/lib/llvm, and if it is a symlink and point to where
    used=None
    if os.path.exists("/usr/lib/llvm"):
        if os.path.islink("/usr/lib/llvm"):
            point_to=os.readlink("/usr/lib/llvm")
            if point_to.startswith("/usr/lib/llvm-"):
                used=point_to[len("/usr/lib/llvm-"):]
    print("Installed versions:")
    for version in versions:
        if  used is not None and used==version:
            print(version+"*","Used")
        else:
            print(version)
    

if __name__ == "__main__":
    main()