#!/usr/bin/env bash

# 使用$HOME/.config/nvims/TD-SKY作为nvim的配置目录
export XDG_CONFIG_HOME=$HOME/.config/nvims
export XDG_DATA_HOME=$HOME/.local/share/nvims
export XDG_STATE_HOME=$HOME/.local/state/nvims
export XDG_CACHE_HOME=$HOME/.cache/nvims
NVIM_APPNAME="TD-SKY" nvim "$@"