#!/usr/bin/env bash

TARGET=$1
MAX_TOTAL_TIME=${2:-10}

cargo +nightly fuzz run $TARGET -- -max_total_time=$MAX_TOTAL_TIME

cargo +nightly fuzz coverage $TARGET

HOST_TUPLE=$(rustc --print host-tuple)

grcov . -s . --binary-path ./target/$HOST_TUPLE/coverage/$HOST_TUPLE/release \
--branch --ignore-not-existing \
-t html \
-o fuzz_coverage_report/

echo "Fuzzing complete. Coverage report generated at fuzz_coverage_report/index.html"

