#!/usr/bin/env python

import pandas as pd
import sys


def xlsx_to_csv(xlsx_file, csv_file):
    # 读取Excel文件
    excel_data = pd.read_excel(xlsx_file)
    # 将数据写入CSV文件
    excel_data.to_csv(csv_file, index=False)


#
if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python xlsx2csv.py <input.xlsx> <output.csv>")
    else:
        xlsx_file = sys.argv[1]
        csv_file = sys.argv[2]
        xlsx_to_csv(xlsx_file, csv_file)
        print(f"Converted {xlsx_file} to {csv_file}")
