[source]

[source.crates-io]
replace-with = "rsproxy-sparse"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[registries]

[registries.crates-io]
protocol = "sparse"

[registries.bfsu]
index = "https://mirrors.bfsu.edu.cn/git/crates.io-index.git"

[registries.bfsu-sparse]
index = "sparse+https://mirrors.bfsu.edu.cn/crates.io-index/"

[registries.hit]
index = "https://mirrors.hit.edu.cn/crates.io-index.git"

[registries.nju]
index = "https://mirror.nju.edu.cn/git/crates.io-index.git"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[registries.rsproxy-sparse]
index = "sparse+https://rsproxy.cn/index/"

[registries.sjtu]
index = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index"

[registries.sjtu-sparse]
index = "sparse+https://mirrors.sjtug.sjtu.edu.cn/crates.io-index/"

[registries.tuna]
index = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

[registries.tuna-sparse]
index = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[registries.ustc]
index = "git://mirrors.ustc.edu.cn/crates.io-index"

[registries.ustc-sparse]
index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[net]
git-fetch-with-cli = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"    # 无论开不开启使用mold作为链接器,该字段都需要存在,它用来指定用什么来提供参数来驱动设计的linker(lld/mold/...)
# rustflags= ["-Clink-arg=-fuse-ld=/usr/lib/llvm/bin/ld.lld","-Clink-arg=-Wl,--no-rosegment"] # 这个注释是为了让flamegraph.rs能够正常追踪调用栈
# linker = "/usr/local/bin/clang"
# rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]

# [build]
# rustc-wrapper = "/usr/bin/sccache"

[cache]
auto-clean-frequency = "1 weeks" # 每周清理一次
